version: '3.8'

services:
  app-traductor:
    image: reaper001/traductor-genai:1.0.0
    ports:            
      - "7860:7860"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    networks:
      - traductor-net
    volumes:
      - mlflow-artifacts-data:/mlflow/artifacts
    deploy:
      replicas: 2       
      restart_policy:
        condition: on-failure

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    ports:
      - "5001:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts
    volumes:
      - mlflow-db-data:/mlflow
      - mlflow-artifacts-data:/mlflow/artifacts
    networks:
      - traductor-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  mlflow-db-data:
  mlflow-artifacts-data:

networks:
  traductor-net:
    driver: overlay